[package]
name = "test_and_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# For benchmarks
[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "fib_bench"
harness = false

[dependencies]
